package com.siamakerlab.vibecoder.server.projects

import com.siamakerlab.vibecoder.server.core.WorkspacePath
import com.siamakerlab.vibecoder.server.error.ApiException
import com.siamakerlab.vibecoder.shared.dto.KeystoreRequestDto
import io.github.oshai.kotlinlogging.KotlinLogging
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.TimeUnit
import kotlin.io.path.exists
import kotlin.io.path.writeText

private val log = KotlinLogging.logger {}

/**
 * Generates an Android signing keystore via the JDK's `keytool` and stores it
 * **outside** the project folder, under `<workspace>/.vibecoder/keystores/<projectId>/`.
 *
 * Why outside the project: signing material must never be committed to the
 * source repo (rule from the user's global CLAUDE.md).
 */
class KeystoreGenerator(private val workspace: WorkspacePath) {

    data class Result(
        val keystoreFile: Path,
        val propertiesFile: Path,
        val alias: String,
    )

    fun generate(projectId: String, appName: String, req: KeystoreRequestDto): Result {
        require(req.alias.isNotBlank()) { "keystore.alias is required" }
        require(req.password.isNotBlank()) { "keystore.password is required" }
        require(req.password.length >= 6) { "keystore.password must be at least 6 chars" }

        // File stem: projectId is already filesystem-safe (validated by registration).
        // appName may contain spaces / unicode which trip Gradle's signing config.
        val stem = projectId
        val dir = workspace.keystoresDir(projectId)
        val keystoreFile = dir.resolve("$stem.keystore")
        val propertiesFile = dir.resolve("$stem-keystore.properties")

        if (keystoreFile.exists()) {
            // Don't silently overwrite — caller can decide policy via a future flag.
            throw ApiException(
                409,
                "keystore_already_exists",
                "$keystoreFile already exists. Delete it before generating a new one.",
            )
        }

        val dname = req.dname ?: DEFAULT_DNAME

        val cmd = listOf(
            "keytool",
            "-genkeypair",
            "-keystore", keystoreFile.toString(),
            "-alias", req.alias,
            "-storepass", req.password,
            "-keypass", req.password,
            "-dname", dname,
            "-keyalg", "RSA",
            "-keysize", "2048",
            "-validity", req.validityDays.toString(),
        )

        val pb = ProcessBuilder(cmd).redirectErrorStream(true)
        val process = pb.start()
        val output = process.inputStream.bufferedReader().readText()
        val finished = process.waitFor(60, TimeUnit.SECONDS)
        if (!finished) {
            process.destroyForcibly()
            throw ApiException(500, "keystore_timeout", "keytool did not finish within 60s")
        }
        if (process.exitValue() != 0) {
            log.warn { "keytool failed (exit=${process.exitValue()}): $output" }
            throw ApiException(
                500,
                "keystore_generation_failed",
                "keytool exited ${process.exitValue()}: ${output.lines().take(3).joinToString(" | ")}",
            )
        }

        // Properties file mirrors what an Android Gradle script would read.
        propertiesFile.writeText(
            """
            |# Generated by vibe-coder on project creation.
            |# Keep this file OUT of version control. Add to .gitignore.
            |storeFile=$keystoreFile
            |storePassword=${req.password}
            |keyAlias=${req.alias}
            |keyPassword=${req.password}
            """.trimMargin(),
        )
        // tighten perms; best-effort on POSIX
        runCatching { keystoreFile.toFile().setReadable(false, false); keystoreFile.toFile().setReadable(true, true) }
        runCatching { propertiesFile.toFile().setReadable(false, false); propertiesFile.toFile().setReadable(true, true) }

        log.info { "keystore generated for project=$projectId at $keystoreFile (alias=${req.alias})" }
        return Result(keystoreFile, propertiesFile, req.alias)
    }

    companion object {
        // Defaults pulled from the user's global CLAUDE.md keystore policy.
        private const val DEFAULT_DNAME =
            "CN=Jangwook Lee, OU=Mobile, O=Sia Makerlab, L=Jecheon, ST=Chungbuk, C=KR"
    }
}
